spring:
  application:
    name: transaction-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: csms-transaction-service-group
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.chargepoint.csms.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      reply-timeout: 1000ms

server:
  port: 9090


kafka:
  request:
    topic: csms-authorization-requests
  reply:
    topic: csms-authorization-responses