spring:
  application:
    name: authentication-service

kafka:
  bootstrap-servers: localhost:29092
  groupid: csms-authorization-service-group
  request:
    topic: csms-authorization-requests
  reply:
    topic: csms-authorization-responses
